package akkatemplate.messages;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Messages.proto

public final class Messages {
    private Messages() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }

    public interface TestRequestOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        // required string message = 1;
        boolean hasMessage();

        String getMessage();
    }

    public static final class TestRequest extends
            com.google.protobuf.GeneratedMessage
            implements TestRequestOrBuilder {
        // Use TestRequest.newBuilder() to construct.
        private TestRequest(Builder builder) {
            super(builder);
        }

        private TestRequest(boolean noInit) {
        }

        private static final TestRequest defaultInstance;

        public static TestRequest getDefaultInstance() {
            return defaultInstance;
        }

        public TestRequest getDefaultInstanceForType() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Messages.internal_static_TestRequest_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Messages.internal_static_TestRequest_fieldAccessorTable;
        }

        private int bitField0_;
        // required string message = 1;
        public static final int MESSAGE_FIELD_NUMBER = 1;
        private java.lang.Object message_;

        public boolean hasMessage() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        public String getMessage() {
            java.lang.Object ref = message_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    message_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getMessageBytes() {
            java.lang.Object ref = message_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                message_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private void initFields() {
            message_ = "";
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) return isInitialized == 1;

            if (!hasMessage()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, getMessageBytes());
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, getMessageBytes());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static Messages.TestRequest parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static Messages.TestRequest parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static Messages.TestRequest parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static Messages.TestRequest parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static Messages.TestRequest parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static Messages.TestRequest parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static Messages.TestRequest parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static Messages.TestRequest parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static Messages.TestRequest parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static Messages.TestRequest parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(Messages.TestRequest prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements Messages.TestRequestOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Messages.internal_static_TestRequest_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Messages.internal_static_TestRequest_fieldAccessorTable;
            }

            // Construct using Messages.TestRequest.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                message_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Messages.TestRequest.getDescriptor();
            }

            public Messages.TestRequest getDefaultInstanceForType() {
                return Messages.TestRequest.getDefaultInstance();
            }

            public Messages.TestRequest build() {
                Messages.TestRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            private Messages.TestRequest buildParsed()
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Messages.TestRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(
                            result).asInvalidProtocolBufferException();
                }
                return result;
            }

            public Messages.TestRequest buildPartial() {
                Messages.TestRequest result = new Messages.TestRequest(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.message_ = message_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Messages.TestRequest) {
                    return mergeFrom((Messages.TestRequest) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Messages.TestRequest other) {
                if (other == Messages.TestRequest.getDefaultInstance()) return this;
                if (other.hasMessage()) {
                    setMessage(other.getMessage());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasMessage()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                        com.google.protobuf.UnknownFieldSet.newBuilder(
                                this.getUnknownFields());
                while (true) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            this.setUnknownFields(unknownFields.build());
                            onChanged();
                            return this;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                this.setUnknownFields(unknownFields.build());
                                onChanged();
                                return this;
                            }
                            break;
                        }
                        case 10: {
                            bitField0_ |= 0x00000001;
                            message_ = input.readBytes();
                            break;
                        }
                    }
                }
            }

            private int bitField0_;

            // required string message = 1;
            private java.lang.Object message_ = "";

            public boolean hasMessage() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            public String getMessage() {
                java.lang.Object ref = message_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    message_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setMessage(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                message_ = value;
                onChanged();
                return this;
            }

            public Builder clearMessage() {
                bitField0_ = (bitField0_ & ~0x00000001);
                message_ = getDefaultInstance().getMessage();
                onChanged();
                return this;
            }

            void setMessage(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000001;
                message_ = value;
                onChanged();
            }

            // @@protoc_insertion_point(builder_scope:TestRequest)
        }

        static {
            defaultInstance = new TestRequest(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:TestRequest)
    }

    public interface TestReplyOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        // required int32 return_code = 1;
        boolean hasReturnCode();

        int getReturnCode();

        // optional string return_msg = 2;
        boolean hasReturnMsg();

        String getReturnMsg();

        // repeated uint64 out_data = 3;
        java.util.List<java.lang.Long> getOutDataList();

        int getOutDataCount();

        long getOutData(int index);
    }

    public static final class TestReply extends
            com.google.protobuf.GeneratedMessage
            implements TestReplyOrBuilder {
        // Use TestReply.newBuilder() to construct.
        private TestReply(Builder builder) {
            super(builder);
        }

        private TestReply(boolean noInit) {
        }

        private static final TestReply defaultInstance;

        public static TestReply getDefaultInstance() {
            return defaultInstance;
        }

        public TestReply getDefaultInstanceForType() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Messages.internal_static_TestReply_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Messages.internal_static_TestReply_fieldAccessorTable;
        }

        private int bitField0_;
        // required int32 return_code = 1;
        public static final int RETURN_CODE_FIELD_NUMBER = 1;
        private int returnCode_;

        public boolean hasReturnCode() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        public int getReturnCode() {
            return returnCode_;
        }

        // optional string return_msg = 2;
        public static final int RETURN_MSG_FIELD_NUMBER = 2;
        private java.lang.Object returnMsg_;

        public boolean hasReturnMsg() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        public String getReturnMsg() {
            java.lang.Object ref = returnMsg_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    returnMsg_ = s;
                }
                return s;
            }
        }

        private com.google.protobuf.ByteString getReturnMsgBytes() {
            java.lang.Object ref = returnMsg_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                returnMsg_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // repeated uint64 out_data = 3;
        public static final int OUT_DATA_FIELD_NUMBER = 3;
        private java.util.List<java.lang.Long> outData_;

        public java.util.List<java.lang.Long>
        getOutDataList() {
            return outData_;
        }

        public int getOutDataCount() {
            return outData_.size();
        }

        public long getOutData(int index) {
            return outData_.get(index);
        }

        private void initFields() {
            returnCode_ = 0;
            returnMsg_ = "";
            outData_ = java.util.Collections.emptyList();
            ;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) return isInitialized == 1;

            if (!hasReturnCode()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeInt32(1, returnCode_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, getReturnMsgBytes());
            }
            for (int i = 0; i < outData_.size(); i++) {
                output.writeUInt64(3, outData_.get(i));
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(1, returnCode_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, getReturnMsgBytes());
            }
            {
                int dataSize = 0;
                for (int i = 0; i < outData_.size(); i++) {
                    dataSize += com.google.protobuf.CodedOutputStream
                            .computeUInt64SizeNoTag(outData_.get(i));
                }
                size += dataSize;
                size += 1 * getOutDataList().size();
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static Messages.TestReply parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static Messages.TestReply parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static Messages.TestReply parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }

        public static Messages.TestReply parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }

        public static Messages.TestReply parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static Messages.TestReply parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static Messages.TestReply parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static Messages.TestReply parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }

        public static Messages.TestReply parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }

        public static Messages.TestReply parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(Messages.TestReply prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements Messages.TestReplyOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Messages.internal_static_TestReply_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Messages.internal_static_TestReply_fieldAccessorTable;
            }

            // Construct using Messages.TestReply.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                returnCode_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                returnMsg_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                outData_ = java.util.Collections.emptyList();
                ;
                bitField0_ = (bitField0_ & ~0x00000004);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Messages.TestReply.getDescriptor();
            }

            public Messages.TestReply getDefaultInstanceForType() {
                return Messages.TestReply.getDefaultInstance();
            }

            public Messages.TestReply build() {
                Messages.TestReply result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            private Messages.TestReply buildParsed()
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Messages.TestReply result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(
                            result).asInvalidProtocolBufferException();
                }
                return result;
            }

            public Messages.TestReply buildPartial() {
                Messages.TestReply result = new Messages.TestReply(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.returnCode_ = returnCode_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.returnMsg_ = returnMsg_;
                if (((bitField0_ & 0x00000004) == 0x00000004)) {
                    outData_ = java.util.Collections.unmodifiableList(outData_);
                    bitField0_ = (bitField0_ & ~0x00000004);
                }
                result.outData_ = outData_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Messages.TestReply) {
                    return mergeFrom((Messages.TestReply) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Messages.TestReply other) {
                if (other == Messages.TestReply.getDefaultInstance()) return this;
                if (other.hasReturnCode()) {
                    setReturnCode(other.getReturnCode());
                }
                if (other.hasReturnMsg()) {
                    setReturnMsg(other.getReturnMsg());
                }
                if (!other.outData_.isEmpty()) {
                    if (outData_.isEmpty()) {
                        outData_ = other.outData_;
                        bitField0_ = (bitField0_ & ~0x00000004);
                    } else {
                        ensureOutDataIsMutable();
                        outData_.addAll(other.outData_);
                    }
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasReturnCode()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                        com.google.protobuf.UnknownFieldSet.newBuilder(
                                this.getUnknownFields());
                while (true) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            this.setUnknownFields(unknownFields.build());
                            onChanged();
                            return this;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                this.setUnknownFields(unknownFields.build());
                                onChanged();
                                return this;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            returnCode_ = input.readInt32();
                            break;
                        }
                        case 18: {
                            bitField0_ |= 0x00000002;
                            returnMsg_ = input.readBytes();
                            break;
                        }
                        case 24: {
                            ensureOutDataIsMutable();
                            outData_.add(input.readUInt64());
                            break;
                        }
                        case 26: {
                            int length = input.readRawVarint32();
                            int limit = input.pushLimit(length);
                            while (input.getBytesUntilLimit() > 0) {
                                addOutData(input.readUInt64());
                            }
                            input.popLimit(limit);
                            break;
                        }
                    }
                }
            }

            private int bitField0_;

            // required int32 return_code = 1;
            private int returnCode_;

            public boolean hasReturnCode() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            public int getReturnCode() {
                return returnCode_;
            }

            public Builder setReturnCode(int value) {
                bitField0_ |= 0x00000001;
                returnCode_ = value;
                onChanged();
                return this;
            }

            public Builder clearReturnCode() {
                bitField0_ = (bitField0_ & ~0x00000001);
                returnCode_ = 0;
                onChanged();
                return this;
            }

            // optional string return_msg = 2;
            private java.lang.Object returnMsg_ = "";

            public boolean hasReturnMsg() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            public String getReturnMsg() {
                java.lang.Object ref = returnMsg_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    returnMsg_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            public Builder setReturnMsg(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                returnMsg_ = value;
                onChanged();
                return this;
            }

            public Builder clearReturnMsg() {
                bitField0_ = (bitField0_ & ~0x00000002);
                returnMsg_ = getDefaultInstance().getReturnMsg();
                onChanged();
                return this;
            }

            void setReturnMsg(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000002;
                returnMsg_ = value;
                onChanged();
            }

            // repeated uint64 out_data = 3;
            private java.util.List<java.lang.Long> outData_ = java.util.Collections.emptyList();
            ;

            private void ensureOutDataIsMutable() {
                if (!((bitField0_ & 0x00000004) == 0x00000004)) {
                    outData_ = new java.util.ArrayList<java.lang.Long>(outData_);
                    bitField0_ |= 0x00000004;
                }
            }

            public java.util.List<java.lang.Long>
            getOutDataList() {
                return java.util.Collections.unmodifiableList(outData_);
            }

            public int getOutDataCount() {
                return outData_.size();
            }

            public long getOutData(int index) {
                return outData_.get(index);
            }

            public Builder setOutData(
                    int index, long value) {
                ensureOutDataIsMutable();
                outData_.set(index, value);
                onChanged();
                return this;
            }

            public Builder addOutData(long value) {
                ensureOutDataIsMutable();
                outData_.add(value);
                onChanged();
                return this;
            }

            public Builder addAllOutData(
                    java.lang.Iterable<? extends java.lang.Long> values) {
                ensureOutDataIsMutable();
                super.addAll(values, outData_);
                onChanged();
                return this;
            }

            public Builder clearOutData() {
                outData_ = java.util.Collections.emptyList();
                ;
                bitField0_ = (bitField0_ & ~0x00000004);
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:TestReply)
        }

        static {
            defaultInstance = new TestReply(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:TestReply)
    }

    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_TestRequest_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_TestRequest_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_TestReply_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_TestReply_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\016Messages.proto\"\036\n\013TestRequest\022\017\n\007messa" +
                        "ge\030\001 \002(\t\"F\n\tTestReply\022\023\n\013return_code\030\001 \002" +
                        "(\005\022\022\n\nreturn_msg\030\002 \001(\t\022\020\n\010out_data\030\003 \003(\004"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        internal_static_TestRequest_descriptor =
                                getDescriptor().getMessageTypes().get(0);
                        internal_static_TestRequest_fieldAccessorTable = new
                                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                                internal_static_TestRequest_descriptor,
                                new java.lang.String[]{"Message",},
                                Messages.TestRequest.class,
                                Messages.TestRequest.Builder.class);
                        internal_static_TestReply_descriptor =
                                getDescriptor().getMessageTypes().get(1);
                        internal_static_TestReply_fieldAccessorTable = new
                                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                                internal_static_TestReply_descriptor,
                                new java.lang.String[]{"ReturnCode", "ReturnMsg", "OutData",},
                                Messages.TestReply.class,
                                Messages.TestReply.Builder.class);
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
    }

    // @@protoc_insertion_point(outer_class_scope)
}
